name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js for use with actions
        uses: actions/setup-node@v1.1.0
        with:
          version: 12.16.0

      - name: Build and Deploy
        run: |
          yarn
          yarn build
          yarn deploy
        env:
          GHOST_API_URL: ${{secrets.GHOST_API_URL}}
          GHOST_CONTENT_API_KEY: ${{secrets.GHOST_CONTENT_API_KEY}}
          SITE_URL: ${{secrets.SITE_URL}}
          FIREBASE_TOKEN: ${{secrets.FIREBASE_TOKEN}}
